# Generated by Django 3.1.2 on 2024-06-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0003_dataset_img_extracted_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(choices=[('worker', 'Worker'), ('ps', 'Parameter Server')], max_length=10)),
                ('ip_address', models.CharField(max_length=15)),
                ('port', models.IntegerField()),
            ],
        ),
    ]
