# Generated by Django 3.1.2 on 2024-08-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0005_training_job_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset_img',
            name='data_path_test',
            field=models.FileField(blank=True, max_length=300, upload_to=''),
        ),
        migrations.AddField(
            model_name='dataset_img',
            name='extracted_path_test',
            field=models.TextField(blank=True),
        ),
    ]
