# Generated by Django 3.1.2 on 2024-08-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0006_auto_20240808_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='training_job',
            name='parameter_settings',
            field=models.TextField(null=True),
        ),
    ]
