# Generated by Django 3.1.2 on 2024-09-07 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0009_chart_charttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainedmodel',
            name='key_attributes',
            field=models.TextField(blank=True),
        ),
    ]
