# Generated by Django 3.1.2 on 2024-09-07 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0010_auto_20240907_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='training_job',
            name='training_log',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='training_job',
            name='dataset_img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_jobs', to='train.dataset_img'),
        ),
    ]
