# Generated by Django 3.1.2 on 2024-09-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0011_auto_20240907_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='training_job',
            name='training_log_history',
            field=models.TextField(null=True),
        ),
    ]
