# Generated by Django 3.1.2 on 2024-09-09 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0013_trainedmodel_dataset_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainedmodel',
            name='dataset_type',
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='dataset_img',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='trained_models', to='train.dataset_img'),
            preserve_default=False,
        ),
    ]
