# Generated by Django 3.1.2 on 2024-09-09 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0014_auto_20240909_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainedmodel',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trained_models', to='train.dataset'),
        ),
        migrations.AlterField(
            model_name='trainedmodel',
            name='dataset_img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trained_models', to='train.dataset_img'),
        ),
    ]
